import { gql } from '@apollo/client';

export const SET_SAMPLE_DATASETS = gql`
  mutation StartSampleDataset($projectId: Int!, $data: SampleDatasetInput!) {
    startSampleDataset(projectId: $projectId, data: $data)
  }
`;

export const LIST_DATA_SOURCE_TABLES = gql`
  query ListDataSourceTables($projectId: Int!) {
    listDataSourceTables(projectId: $projectId) {
      name
      columns {
        name
        type
      }
    }
  }
`;

export const AUTO_GENERATED_RELATIONS = gql`
  query AutoGeneratedRelations($projectId: Int!) {
    autoGenerateRelation(projectId: $projectId) {
      id
      displayName
      referenceName
      relations {
        fromModelId
        fromModelReferenceName
        fromColumnId
        fromColumnReferenceName
        toModelId
        toModelReferenceName
        toColumnId
        toColumnReferenceName
        type
        name
      }
    }
  }
`;

export const SAVE_DATA_SOURCE = gql`
  mutation SaveDataSource($projectId: Int!, $data: DataSourceInput!) {
    saveDataSource(projectId: $projectId, data: $data) {
      type
      properties
    }
  }
`;

export const UPDATE_DATA_SOURCE = gql`
  mutation UpdateDataSource($projectId: Int!, $data: UpdateDataSourceInput!) {
    updateDataSource(projectId: $projectId, data: $data) {
      type
      properties
    }
  }
`;

export const SAVE_TABLES = gql`
  mutation SaveTables($projectId: Int!, $data: SaveTablesInput!) {
    saveTables(projectId: $projectId, data: $data)
  }
`;

export const SAVE_RELATIONS = gql`
  mutation SaveRelations($projectId: Int!, $data: SaveRelationInput!) {
    saveRelations(projectId: $projectId, data: $data)
  }
`;

export const GET_SCHEMA_CHANGE = gql`
  query SchemaChange($projectId: Int!) {
    schemaChange(projectId: $projectId) {
      deletedTables {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      deletedColumns {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      modifiedColumns {
        sourceTableName
        displayName
        columns {
          sourceColumnName
          displayName
          type
        }
        relationships {
          displayName
          referenceName
        }
        calculatedFields {
          displayName
          referenceName
          type
        }
      }
      lastSchemaChangeTime
    }
  }
`;

export const TRIGGER_DATA_SOURCE_DETECTION = gql`
  mutation TriggerDataSourceDetection($projectId: Int!) {
    triggerDataSourceDetection(projectId: $projectId)
  }
`;

export const RESOLVE_SCHEMA_CHANGE = gql`
  mutation ResolveSchemaChange($projectId: Int!, $where: ResolveSchemaChangeWhereInput!) {
    resolveSchemaChange(projectId: $projectId, where: $where)
  }
`;
